### ISSUE TITLE
SLF4J warnings

### ISSUE THREAD

**Issue by scarlettllc** [HXX97/EDGQA#1]
When running the EDGQA system, are the following warnings imperative?

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by yhshu** [comment]
SLF4J has been added to Maven, please update your code and reload the Maven project.
