### ISSUE TITLE
Add check of withStdOutMap.get(writer) when decide whether to execute System.out.print(str)

### ISSUE THREAD

**Issue by scarlettllc** [HXX97/EDGQA#2]
In the file "main/src/main/java/cn/edu/nju/ws/edgqa/utils/LogUtil.java", in the function "public static void print(String writer, String str, LogType logType)", it's better to use "withStdOutMap.containsKey(writer) && withStdOutMap.get(writer)" instead of only "withStdOutMap.containsKey(writer)" to decide whether to execute the code "System.out.print(str)". Otherwise, the variable "withStdOut" doesn't play its due role and seems redundant.

**Comment by yhshu** [comment]
Problem fixed.
