### ISSUE TITLE
Use phrase "time for solving the current question" instead of "current time"  to avoid ambiguity

### ISSUE THREAD

**Issue by scarlettllc** [HXX97/EDGQA#3]
In the file "src/main/java/cn/edu/nju/ws/edgqa/main/EDGQA.java", in the function "private static void computeMetrics(long startTime, CumulativeIRMetrics cumulativeIRMetrics, CumulativeIRMetrics QALDcumulativeIRMetrics, int quesIdx, long questionStartTime, int sparqlTemplateId, String goldenSparql, EDG edg, IRMetrics localIRMetrics, IRMetrics localQALDIRMetrics)", when show the information of the time for solving the current question, it's better to use phase "time for solving the current question" instead of "current time". Otherwise, some people may regard the "current time" as "time from the start of the system to the present" or "current time(time and date)".

**Comment by yhshu** [comment]
Problem fixed
