### ISSUE TITLE
Why do I need to rewrite the QALD SPARQL in order to run the QA system?

### ISSUE THREAD

**Issue by scarlettllc** [HXX97/EDGQA#4]
I have noticed that when EDGQA deals with the QALD dataset, before using Query Factory to create the goldenQuery, there is a step which use "Preprocessor.rewriteQALDSparql" to rewrite the SPARQL for QALD. I wonder why this step is in need.
`
goldenSparql = Preprocessor.rewriteQALDSparql(goldenSparql);  // rewrite sparql for qald
`
`
Query goldenQuery = QueryFactory.create(goldenSparql, Syntax.syntaxARQ);
`
`
goldenAnswer.addAll(KBUtil.getQueryStringResult(goldenQuery)); // the golden answers
`

**Comment by yhshu** [comment]
The SPARQL query in QALD-9 could not work correctly on our Virtuoso endpoint, so we did this re-write.
It didn't change any semantics of the input SPARQL query.
