### ISSUE TITLE
Virtuoso Install?

### ISSUE THREAD

**Issue by n-sheikh** [HXX97/EDGQA#7]
What version of Virtuoso is required to run EDGQA? I get an error with KBUtil initialising. 

![image](https://user-images.githubusercontent.com/53005542/150266535-df85869d-b59a-44c2-a849-222ca8a35f10.png)

**Comment by HXX97** [comment]
Have you started your local virtuoso service? If so, change the URLs in KBUtil.java according to your virtuoso settings. 
For example, `CORE_KB_1604` gives the HTTP URL of dbpedia1604, and `CORE_KB_JDBC_1604` gives the JDBC URL.
![image](https://user-images.githubusercontent.com/23658059/150269155-5ccd8cd8-d90c-4e04-8b06-90cbf16e9b8a.png)

As for the version of virtuoso, we use version `07.20.3229`. Please refer to the [document](http://vos.openlinksw.com/owiki/wiki/VOS/VOSUbuntuNotes) to learn more about the installation of virtuoso.

**Comment by n-sheikh** [comment]
Although I have the http url I do not have the jdbc url, where would I find this? I do have virtuoso running.

**Comment by HXX97** [comment]
You can check the parameter `ServerPort`  in your setting file, the default port is 1111. So your JDBC url should be "jdbc:virtuoso://<YOUR_IP_ADDRESS>:<YOUR_SERVER_PORT>"
![image](https://user-images.githubusercontent.com/23658059/150274128-956742a8-bc71-44c6-93a1-0a92d8b8044a.png)

**Comment by n-sheikh** [comment]
Thanks this did resolve my issue.
